name: Check Prettier

on: [ pull_request ]

jobs:
    chequear:
        runs-on: ubuntu-latest

        steps:
            - name: Enviar archivo
              uses: actions/checkout@v4 
            - name: installar prettier 
              run:  npm i prettier 
            - name: Correr check prettier 
              run:  npx prettier . --check