name: Check Prettier

on: [pull_request]

jobs:
  chequear:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código del repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4 

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Cambiar por la versión deseada

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: npm ci
      # 4. Ejecutar Prettier para Formatear archivos
      - name: Formatear archivos
        run: npx prettier . --write
      # 5. Ejecutar Prettier para verificar el formato del código
      - name: Verificar formato con Prettier
        run: npx prettier . --check
