name: Check Prettier

on: [ pull_request ]

jobs:
    chequear:
        runs-on: ubuntu-latest

        steps:
            - name: Enviar archivos
              uses: actions/checkout@v4 
            - name: Correr check prettier 
              run:  npx prettier. --check